spring.application.name=api
jwts.security=9gmSBJ6n3khd1o25TIRy35Z8T6fdEJCwUxDJe2zeY6g=
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true